export const CONSTITUTION = {
  title: "構成代碼",
  en: "CONSTITUTION CODE",
  record: "MATERIAL COMPOSITION RECORD",
  result: "分析结果",
  scan: "ANALYZE(SAMPLE_001::COMPOSITION)",
  traces: {
    "01": "TRACE::TOP_NOTE",
    "02": "TRACE::HEART_NOTE",
    "03": "TRACE::BASE_NOTE",
  },
  streams: {
    top: [
      "TRACE::TOP_NOTE",
      "SCAN::RUBBER",
      "MATERIAL::02",
      "MATCH::87.4%",
      "TRACE::TOP",
      "RUBBER::WET",
      "ANALYZE::CONDUCTOR",
      "RATIO::0.73",
      "TRACE::TOP_NOTE",
      "MATCH::91%",
      "ID::T-01",
      "PIPE::OPTIC",
      "GAS::CARRIER",
    ],
    heart: [
      "TRACE::HEART_NOTE",
      "SCAN::VIRAL",
      "MATERIAL::07",
      "TRACE::GEL",
      "MATCH::94.2%",
      "SILICONE::SOFT",
      "TRACE::HEART",
      "ANALYZE::PEACH",
      "SIGNAL::0.81",
      "COOLANT::OK",
      "PULP::ELEC",
      "MATCH::88%",
    ],
    base: [
      "TRACE::BASE_NOTE",
      "SCAN::SILICONE",
      "MATERIAL::11",
      "CARBON::TRACE",
      "MATCH::89.7%",
      "TRACE::BASE",
      "RESIDUE::DETECTED",
      "2-DDG::0.42",
      "ANALYZE::CARBON",
      "OIL::HEAVY",
      "ASH::PRESENT",
      "MATCH::64%",
    ],
  },
  groups: [
    {
      id: "01",
      zh: "前調",
      en: "TOP",
      items: ["光脈導管", "工業橡膠", "載氣"],
    },
    {
      id: "02",
      zh: "中調",
      en: "HEART",
      items: ["彌散病毒", "軟質矽膠", "電子桃漿", "冷卻劑"],
    },
    {
      id: "03",
      zh: "後調",
      en: "BASE",
      items: ["重質矽油", "老化橡膠", "碳化殘渣", "2-DDG"],
    },
  ],
} as const;
