export const CONSTITUTION = {
  title: "構成代碼",
  en: "CONSTITUTION CODE",
  record: "MATERIAL COMPOSITION RECORD",
  result: "分析结果",
  scan: "ANALYZE(SAMPLE_001::COMPOSITION)",
  traces: {
    "01": "TRACE::TOP_NOTE",
    "02": "TRACE::HEART_NOTE",
    "03": "TRACE::BASE_NOTE",
  },
  streams: {
    top: [
      "TRACE::TOP_NOTE",
      "SCAN::RUBBER",
      "MATERIAL::02",
      "MATCH::87.4%",
      "RUBBER::WET",
      "ANALYZE::CONDUCTOR",
      "RATIO::0.73",
      "TRACE::TOP_NOTE",
      "MATCH::91%",
    ],
    heart: [
      "TRACE::HEART_NOTE",
      "SCAN::SILICONE",
      "MATERIAL::07",
      "MATCH::82.1%",
      "VIRUS::DIFFUSE",
      "ANALYZE::NEURAL",
      "RATIO::0.61",
      "TRACE::HEART_NOTE",
      "MATCH::94%",
    ],
    base: [
      "TRACE::BASE_NOTE",
      "SCAN::SILICONE_OIL",
      "MATERIAL::11",
      "MATCH::79.3%",
      "CARBON::RESIDUE",
      "ANALYZE::THERMAL",
      "RATIO::0.88",
      "TRACE::BASE_NOTE",
      "MATCH::96%",
    ],
  },
  groups: [
    {
      id: "01",
      zh: "前調",
      en: "TOP",
      items: ["光脈導管", "工業橡膠", "載氣"],
    },
    {
      id: "02",
      zh: "中調",
      en: "HEART",
      items: ["彌散病毒", "軟質矽膠", "電子桃漿", "冷卻劑"],
    },
    {
      id: "03",
      zh: "後調",
      en: "BASE",
      items: ["重質矽油", "老化橡膠", "碳化殘渣", "2-DDG"],
    },
  ],
} as const;
